title: SSISCataloger
description: the SSIS Catalog Migration Wizard
show_downloads: false
theme: jekyll-theme-dinky

# Includes an icon in the footer for each user name you enter
footer-links:
  github: kr55
  linkedin: kr55

